name: CoreBankEC CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ”„ Checkout del cÃ³digo
      uses: actions/checkout@v3

    - name: ğŸ Configurar Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: ğŸ“¦ Instalar dependencias
      working-directory: core-bankec-python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8

    - name: âœ… AnÃ¡lisis estÃ¡tico con flake8
      working-directory: core-bankec-python
      continue-on-error: true
      run: |
        echo "Ejecutando flake8..."
        flake8 app/ --ignore=E501,E302,W293,E261

    - name: ğŸ³ Construir imagen Docker
      working-directory: core-bankec-python
      run: |
        docker build -t core-bankec .
